### ISSUE TITLE
when JS SDK of this project will update ?

### ISSUE THREAD

**Issue by mtariqsajid** [TwilioDevEd/browser-calls-laravel#174]
Hi, can you tell me when you will update to new JS sdk of twilio ?

**Comment by bld010** [comment]
Hi @mtariqsajid, Twilio Developer Educator here. 

Unfortunately, I don't have an exact date for you, but this project is at the top of my list for updating. 

In the meantime, the [Voice JS SDK Quickstart for PHP](https://github.com/TwilioDevEd/voice-javascript-sdk-quickstart-php) is updated to use Version 2, so that can serve as a guide for you.  The [Migration Guide](https://www.twilio.com/docs/voice/sdks/javascript/migrating-to-js-voice-sdk-20) may also help.

**Comment by mtariqsajid** [comment]
Looking forward for the update 
Thank you for the update
